### ISSUE TITLE
PR aka Prague Proposal

### ISSUE THREAD

**Issue by pavrych** [bitsongofficial/delegation-program#11]
## Type of Proposal

- [ ] Feature Request (e.g. functionality)

- [x ] Economic Model

- [ ] Underlying Technology (e.g. performance)

- [ ] Application Development

- [ x] Marketing/Community Building

- [x ] Communication Channels

- [ ] Documentation

- [ ] Others

## Background

I'm very experienced validator, project manager and community leader
## Describe The Proposal (No more than 50 words)
I can do common advisoring and further project development, including economic models etc

## Expected Outcome
Stable growth, right econimic models, strong community

## Contact Information
Discord: Prague#9624

## For Admin Use

- [ ] Not duplicate proposal
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by BitGlad1** [comment]
Hi there,

Thanks for your proposal.

Please fill in the Timetable too and explain a little bit more in detail how you aim to contribute to the ecosystem growth, which tools are you going to use and why do you expect a positive impact following your actions.

Regards
