### ISSUE TITLE
MissionControl Proposal

### ISSUE THREAD

**Issue by MissionControlValidator** [bitsongofficial/delegation-program#16]
---
name: Proposal Request
about: Create a proposal request to take part in the delegation program
---

## Type of Proposal

- [ ] Feature Request (e.g. functionality)

- [ ] Economic Model

- [ ] Underlying Technology (e.g. performance)

- [x] Application Development

- [ ] Marketing/Community Building

- [ ] Communication Channels

- [x] Documentation

- [ ] Others

## Background

We are a group of Italian friends. 
We started our adventure in the POS world a year ago on the Terra blockchain and after a few months we also started a validator on emoney.
We recently opened our validator on Bitsong because we want to support this interesting project.

## Describe The Proposal (No more than 50 words)

We are developing alerting tools for validators and when ready everything will be released as open source. 
We are also planning to make documentations to support node operators and new validators.

## Expected Outcome

With our projects we hope to help validators and node operators improve the management of their infrastructure.

## Contact Information

support@mcontrol.ml

## For Admin Use

- [ ] Not duplicate proposal
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by BitGlad1** [comment]
Please fill in the timetable and explain a little bit more in details how do you plan to apply those tools to BitSong Ecosystem.

**Comment by MissionControlValidator** [comment]
Hi, this is our timetable:

| Implementation Steps | Time Consuming |
| -------------------- | -------------- |
| Step by step guide and documentation for validators and node operators  | two weeks |
| Monitoring and alerting tool for validators, with notifications on telegram and discord | one month |
| Bitsong token and chain analytrics dashboard, you can find an example of those we did for Terra [here](https://analytics.mcontrol.ml/luna/) | one/two months, it depends on how many data sources we can find |
