### ISSUE TITLE
Jetlife validator delegation

### ISSUE THREAD

**Issue by jetlag666** [bitsongofficial/delegation-program#2]
## Type of Proposal

- Team delegation.

## Background

Hello, I'm a veteran validator for multiples blockchains and I'm proud to support this network!

## Describe The Proposal (No more than 50 words)

This proposal is for a delegation from the Bitsong team to my validator.

My validator is hosted in a tier 1 cloud host and monitored 24/7 by myself.

## Expected Outcome

My target is 99% uptime for maximum performance and security for the Bitsong blockchain.

## Contact Information

gamah@jetlifestaking.org

**Comment by BitGlad1** [comment]
Hi there,

Beside keeping your node up and secure, is there any other way you're looking forward to help the ecosystem growth through?

**Comment by jetlag666** [comment]
Hello yes, but since im not a dev my options are limited, one of the thing that I would like to do is translating bitsong documentation, I already did it for others blockchain like Mina and Akash network.

**Comment by BitGlad1** [comment]
Hi there and thanks for your reply.
We'll further evaluate your proposal.
Stay tuned
