### ISSUE TITLE
CommunityStaking application

### ISSUE THREAD

**Issue by CommunityStaking** [bitsongofficial/delegation-program#20]
### Validator address

bitsongvaloper1zugs5wtmt98949msgwchawr5cal7h32s8na0r9

### On Chain Data

- [X] I confirm to have set my validator information on chain

### Contact information

https://t.me/CommunityStaking_validator

### Application categories

Participation in the BitSong ecosystem, None core development

### Details

I'd like to submit my contribution into setting up the Delegation Program and DAO concept together with Felix (not sure what category that falls under). Making a claim on the CommunityStaking Uptime as well as the following:

Commission restake: 100%
Self delegation: 2 accounts (DM me for the 2nd account)

### Goals

We're all about the community. Basically helping people get into great projects on the blockchain. We spend out time talking to people in the cosmos community all around and try to bridge to gap between the still very innovative and technical side of crypto/blockchain and the every day person that does need that bit of extra help to get on board. On the BitSong organizational side we can provide help with the organization side, User Acceptance Testing.

### Timetable

On a continuous basis.

**Comment by ctrl-Felix** [comment]
Participation in the DAO is a ``Participation in the BitSong ecosystem`` in my opinion

**Comment by ctrl-Felix** [comment]
Score: 2925
https://l.ctrl-felix.de/F6iCU

Thank you for your contribution, especially to the DAO

**Comment by ctrl-Felix** [comment]
New Score: 2970
https://l.ctrl-felix.de/yQxga

Updated Rank
