### ISSUE TITLE
DAO app

### ISSUE THREAD

**Issue by TheCrazyStaker** [bitsongofficial/delegation-program#21]
### Validator address

bitsongvaloper1um889kzz9gyxlwtrgs6mc9sdwwx8z2kekudytd

### On Chain Data

- [x] I confirm to have set my validator information on chain

### Contact information

cristi_an_m#7885

### Application categories

Uptime, Commission restake, Participation in the BitSong ecosystem, Running relayers

### Details

I am thinking to set up a relayer node as well.

**Comment by ctrl-Felix** [comment]
Do you plan to set them up before the beginning of the epoch (1st June) or somewhen in the epoch?

**Comment by TheCrazyStaker** [comment]
I will set it up before 1st of June.

**Comment by ctrl-Felix** [comment]
Alright. Thank you for the info. What is the target ratio for the comission restake?

**Comment by TheCrazyStaker** [comment]
10% of the commission will be restaked

**Comment by CommunityStaking** [comment]
Hello Stake Me Higher, please make sure you have the prerequisites of the delegation program covered asap or you will lose the BitSong delegation.

**Comment by TheCrazyStaker** [comment]
Yes, everything is set. If anything else is needed, I will be here.
Thank you!

**Comment by TheCrazyStaker** [comment]
Hello, 
I've also set up a relayer, addresses bellow:
osmo13ant6q5jphhvn000k23455ycc2tu907d2c2344
bitsong1ssfe28uyfvmg6des2tcjshpe5qckscx74kgm3p

**Comment by ctrl-Felix** [comment]
New Score: 3422
https://bitsong.ctrl-felix.de/calculator?calculate=true&uptime=100&rank=77&selfDelegation=901&votingPower=10121&comissionRestake=100&score=1882.7378717518031 (Link generation broken)
