### ISSUE TITLE
freak12techno | Validator - Application for the delegation from the DAO

### ISSUE THREAD

**Issue by freak12techno** [bitsongofficial/delegation-program#23]
### Validator address

bitsongvaloper14rvn7anf22e00vj5x3al4w50ns78s7n42rc0ge

### On Chain Data

- [X] I confirm to have set my validator information on chain

### Contact information

freak12techno | Validator#1151 / freak12techno@gmail.com / @random_user00101 @ Telegram

### Application categories

Uptime, Commission restake, Self delegation, None core development, Running an public rpc/api

### Details

Here's some info on our validators:
Website: https://freak12techno.github.io/validators
Telegram channels with updates: https://t.me/freak12techno_validator
For now this validator is operated by me solely and there's also my brother helping with promoting.

Anyways, straight to the contributions.
We aren't that active in promoting Bitsong itself, but I try to help other validators a lot (as technical things is something I can help with the most).
I write information that may help validators increase their security and observability on our Telegram channel.
Also I wrote some tools for validators to be able to observe their nodes better. You can find them on my website (https://freak12techno.github.io), but here are the most useful ones:
- https://github.com/solarlabsteam/tendermint-exporter - a Prometheus exporter to see the node stats (voting power, catching up, time since latest block)
- https://github.com/solarlabsteam/cosmos-exporter - a Prometheus exporter to get the info from blockchain on specific wallets/validators/general chain params
- https://github.com/solarlabsteam/cosmos-transactions-bot - a Telegram/Slack bot to be notified on new txs matching the specific filter
Currently most of the delegation we have is the one from the team (hi Angelo) and self-stake and we plan to re-stake more.
Our validator has ReStake support enabled, so everyone can give our bot wallet grants and forget about manual compounding.
Recently, we set up our public RPC node (we'll also enable statesync on it later): https://rpc.bitsong.freak12techno.io (Tendermint RPC),  https://api.bitsong.freak12techno.io/ (cosmos-sdk LCD API) and  `4c280db61f8c052dcc3c0c281d98c21f756f5c7f@rpc.bitsong.freak12techno.io:26656` (Tendermint p2p peer).
Also, we maintain the instance of missed-blocks-checker for Bitsong validators: https://t.me/bitsong_missed, so other validators can see their missed blocks.
Finally, we provide a set of ansible playbooks to bootstrap and secure a fullnode, you can find it here: https://github.com/freak12techno/ansible-cosmos

### Goals

We plan to cover the server fees and re-stake the rest, as well as with other validators (to gain more profits from the validator in the long-term).

**Comment by ctrl-Felix** [comment]
Hi, thank you very much for your detailed application. I love the tools you've made! Did you also enable api on the rpc node you provided? I couldn't find it

**Comment by freak12techno** [comment]
Sorry, forgot to set up a proxy pass for lcd endpoints, will do today.

**Comment by freak12techno** [comment]
Done, it's here: https://rpc.bitsong.freak12techno.io/.
I'm also trying now to figure out how to proxy-pass gRPC, will post here if I'll succeed.

**Comment by freak12techno** [comment]
@ctrl-Felix adding to the list of contributions: I've deployed an instance of missed-blocks-checker (which I also maintain) on Bitsong, so validators can see the missed blocks, it's available here: https://t.me/bitsong_missed. I'll also share in chat, so other would be aware.

**Comment by freak12techno** [comment]
also forgot to add that I maintain a set of ansible-playbooks to bootstrap a node: https://github.com/freak12techno/ansible-cosmos, also added it to description

**Comment by freak12techno** [comment]
To clarify on a restake commission: for now it's pointless to sell the rewards as it's way smaller than the servers rent, so we'll restake everything (100%) unless it becomes at least somewhat profitable.

**Comment by Voynitskiy** [comment]
Will stake 100%

**Comment by ctrl-Felix** [comment]
> Will stake 100%

Can you put that to your own application please :)

**Comment by TheCrazyStaker** [comment]
Hello freak12techno,
According to our calculation, you have 1520 points.
Thank you for contributing in Bitsong ecosystem, we rewarded this as you will see in the calculation link bellow.
https://l.ctrl-felix.de/cxQDJ

**Comment by ctrl-Felix** [comment]
New Score: 
https://l.ctrl-felix.de/h6ViE

Change Rank from 40 (default) to 88 (adjusted)
