### ISSUE TITLE
Tedcrypto | Validator | Promoting stake

### ISSUE THREAD

**Issue by joshlopes** [bitsongofficial/delegation-program#24]
### Validator address

bitsongvaloper1qxw4fjged2xve8ez7nu779tm8ejw92rv0vcuqr

### On Chain Data

- [X] I confirm to have set my validator information on chain

### Contact information

Josh_Lopes#0001

### Application categories

Uptime, Commission restake, Self delegation, None core development

### Details

Tedcrypto is a new brand created by me Luis and currently running solely by me from the beginning of this year. 
I've been personally investing in the cosmos since last year and driven by its ecosystem decided to promote and secure more networks by validating them, at the same time trying to disrupt the centralisation in the decentralisation which we can see in many chains (same top validators in all blockchains...). 
Committed to providing more value to PoS and to cosmos in general, I've been working on an application named TedLotto. Which promotes a healthy delegation system, wherein turn we encourage delegators to delegate and secure the network by offering them free tickets based on the amount staked on our validator (the system actually allows more validators to participate! will write this below) and have a weekly chance of getting a jackpot price. You can read more about this project here: https://docs.tedcrypto.io, the app can be found here: https://lotto.tedcrypto.io

I've been promoting bitsong on Twitter and on private channels personally and because I love music and listen to o music for the most part of my day, I'm very bullish on bitsong projects and concepts.

** More validators in TedLotto
When I created TedLotto our ideal was to bring more validators on board, they would help by increasing the Lotto Wallet value and in turn, TedLotto would consider delegations from that validator in the ticket system. E.g.: If validator X wanted to join, then all dPoS would get Y amounts of tickets based on the Z stacked amount. We have not actively started looking for this, but if you are a validator and you want to join, let me know!

### Goals

Short goal: Increase our community, help further bitsong project and promoting it. Increase our reach to bisong community. Promote and create a Lotto Wallet (I'm going to create one Lotto Wallet next week 09/05/2022, with 400€ worth of tokens to kick it off). 2% of our 10% commission (20%) will be invested in this Lotto wallet to increase it's value over time. All the remaining rewards will be re-delegated to further increase rewards overtime and faster increase the lotto rewards too. We are doing this for CRBRUs already, I haven't configured these scripts on Bitsong yet!

Long goal: I want to be able to work as a validator full time, increasing my reach on multiple projects and be able to spend my time working full time on blockchain projects. I've been accepted in the IDA which starts next week. 

<img width="697" alt="image" src="https://user-images.githubusercontent.com/3440849/167258518-521d3a05-7f43-47ed-bc47-4cac32cf156a.png">

I've started working on full rest and friendly API that will have pre-formatted values and well-documented data from chains without having to overstress public chains. For now, is a centralised app. It aims to be a open API which anyone can use and create websites such mintscan on the fly. I believe there is a lot of potential having this data organised outside the blockchain in a relation database so further developers can create more applications more easily using just basic HTTP requests.

### Timetable

TedLotto is a project that never stops, having external help with the rewards we get from delegations, will definitively help increase the lotto wallet faster and be more interesting to delegators and to the bitsong community. 

In the long term, based on the number of delegations we get we don't need as many tokens as the project will become self-sustained.

**Comment by joshlopes** [comment]
https://www.mintscan.io/bitsong/account/bitsong1k652lq822mnvu9furfmmq3wsmufvvyg9pzljrq lotto wallet -- tokens bought and staked to Tedcrypto.

Script to claim rewards and split node rewards as follow

```shell
#!/bin/bash
CHAIN=bitsong-2b
DELEGATOR=bitsong1qxw4fjged2xve8ez7nu779tm8ejw92rvwgy4s7
ACC_NAME=xxx
PASWD=xxx
BINARY="bitsongd"
DENOM=ubtsg
GAS_FEES=5000
MIN_BALANCE=1000000

LOTTO_WALLET=bitsong1k652lq822mnvu9furfmmq3wsmufvvyg9pzljrq
LOTTO_PERCENTAGE=60

VALIDATOR=bitsongvaloper1qxw4fjged2xve8ez7nu779tm8ejw92rv0vcuqr
VALIDATOR_PERCENTAGE=40

echo -e "\n\n===== Running script =====\n"

BAL=$(${BINARY} query bank balances ${DELEGATOR} -o json | jq -r '.balances | .[].amount');
echo -e "BALANCE: ${BAL}${DENOM}\n\n"
echo -e "-- Claim rewards -- \n\n"
echo -e "${PASWD}\n${PASWD}\n" | ${BINARY} tx distribution withdraw-rewards ${VALIDATOR} --chain-id ${CHAIN} --from ${ACC_NAME} --commission -y --fees ${GAS_FEES}${DENOM}

sleep 10

echo -e "\n\n-- Claim successful --\n\n"

BAL=$(${BINARY} query bank balances ${DELEGATOR} -o json | jq -r '.balances | .[].amount');
BAL=$((BAL - 1000000));
LOTTO_BAL=$(echo "scale=2 ; (${BAL}/${LOTTO_PERCENTAGE})" | bc);
VALIDATOR_BAL=$(echo "scale=2 ; (${BAL}/${VALIDATOR_PERCENTAGE})" | bc);

echo -e "BALANCES:\nTotal: ${BAL}${DENOM}\nLotto: ${LOTTO_BAL}${DENOM}\nValidator: ${VALIDATOR_BAL}${DENOM}\n\n"

if [[ (${LOTTO_BAL} > ${MIN_BALANCE}) && (${VALIDATOR_BAL} > ${MIN_BALANCE}) ]]
then
        echo -e "Staking ${VALIDATOR_BAL} to validator ${VALIDATOR}\n"
        echo -e "${PASWD}\n${PASWD}\n" | ${BINARY} tx staking delegate ${VALIDATOR} ${VALIDATOR_BAL}${DENOM} --chain-id ${CHAIN} --from ${ACC_NAME} -y --fees ${GAS_FEES}${DENOM}

        sleep 10

        echo -e "\n\nSending ${LOTTO_BAL} to lotto wallet\n"
        echo -e "${PASWD}\n${PASWD}\n" | ${BINARY} tx bank send ${DELEGATOR} $LOTTO_WALLET ${LOTTO_BAL}${DENOM} --chain-id ${CHAIN} --from ${ACC_NAME} -y --fees ${GAS_FEES}${DENOM}
else
        echo -e "\n\nMin balance not met.\nCurrent Lotto Balance: ${LOTTO_BAL}\nCurrent Validator balance: ${VALIDATOR_BAL}\nMin Balance: ${MIN_BALANCE}\n\n"
fi
```

**Comment by joshlopes** [comment]
We will be restaking 60% and take 40% to TedLotto which is another product we offer to promote and secure the network. Once we get to 20K of tokens we will reduce the percentage we put on Lotto by 20% and restaking that

**Comment by ctrl-Felix** [comment]
Score: 1921
https://l.ctrl-felix.de/kgKmL

Thank you for your application and participation!
