### ISSUE TITLE
AlxVoy | Validator

### ISSUE THREAD

**Issue by Voynitskiy** [bitsongofficial/delegation-program#25]
### Validator address

bitsongvaloper138zp40g5pnjg4e7a24j5035q2f7nzwfec8ruee

### On Chain Data

- [X] I confirm to have set my validator information on chain

### Contact information

Voynitskiy | AlxVoy#7896

### Application categories

Uptime, Commission restake, Self delegation

### Details

The main thing for me is uptime, I monitor the server very carefully. I redelegate all the income from the validator and also plan to increase my delegation.

I also take updates very seriously and always adjust my plans so as not to let you down.

I plan to launch relayers in the future.

My website: [https://voynitskiy.com](https://voynitskiy.com)

### Goals

I plan to become a full-fledged validator of the Bit Song network and be useful for this role.

**Comment by Voynitskiy** [comment]
Will restake 100%

**Comment by TheCrazyStaker** [comment]
corrected calculation https://l.ctrl-felix.de/tlbqK
new scoring: 2430 pts
