### ISSUE TITLE
Hammerfest application

### ISSUE THREAD

**Issue by sideEffect117** [bitsongofficial/delegation-program#26]
### Validator address

bitsongvaloper1eflcvhl567dsdf0qlz48jth89a8qv8tytxpllz

### On Chain Data

- [X] I confirm to have set my validator information on chain

### Contact information

Discord: Hammerf3st#1457

### Application categories

Uptime, Commission restake, Self delegation

### Details

I am a professional node operator and validator with good experience in various networks and I can resolve technical problems with node. My goal is the uninterrupted operation of the node. Also I plan to restake comission from validator

**Comment by ctrl-Felix** [comment]
What is your target in the comission restake? What ratio of your comission do you want to keep or restake?

**Comment by sideEffect117** [comment]
My target is increasing my stake. I think i will be restake 100% of incoming comission

**Comment by CommunityStaking** [comment]
Hello hammerfest, please make sure you have the prerequisites of the delegation program covered asap or you will lose the BitSong delegation. In regards to the Commission restake, it's a commitment for the duration of the epoch (3 months, starting 1e of June 2022).

**Comment by TheCrazyStaker** [comment]
Hello sideEffect117,
Your score is 1120 pcts. Link bellow:
https://l.ctrl-felix.de/7FU6y

**Comment by ctrl-Felix** [comment]
Missing website and logo (mintscan too)

**Comment by TheCrazyStaker** [comment]
new calculation https://l.ctrl-felix.de/DWdm1
scoring stays 1020 pcts
