### ISSUE TITLE
Hathor Nodes Delegation

### ISSUE THREAD

**Issue by Pharaon1993** [bitsongofficial/delegation-program#27]
### Validator address

bitsongvaloper1t26ag4sn8075dk27d8zp6dh30prnqzymcnee5a

### On Chain Data

- [X] I confirm to have set my validator information on chain

### Contact information

pharaon1993@protonmail.com

### Application categories

Uptime, Commission restake, Self delegation, Other

### Details

Uptime - 100%
Commission - 5%
Self Delegation - I delegate almost all of my rewards, w/ a self delegation of 5.44% atm.
Other - I provide governance record information for the Bitsong Delegations DAO.

**Comment by ctrl-Felix** [comment]
Hi, thank you very much for your application. May I ask you what target ratio you want to achieve with the comission restaking? You said almost, is that somewhere between 80%-90%?

**Comment by Pharaon1993** [comment]
> Hi, thank you very much for your application. May I ask you what target ratio you want to achieve with the comission restaking? You said almost, is that somewhere between 80%-90%?

Currently I delegate 100% of my rewards. In the future, I might delegate 80-90% of my staking rewards and use the rest to cover node operating costs, but no plans to do that in the foreseeable future.

**Comment by CommunityStaking** [comment]
Hello Hathor Node, please make sure you have the prerequisites of the delegation program covered asap or you will lose the BitSong delegation. In regards to the Commission restake we ask what you will commit during the epoch (3 months, starting 1 June 2022).

**Comment by TheCrazyStaker** [comment]
Hello Pharaon1993
This is your calculation, considering that you will restake 90% of your commission. 
You have 959 points. Link bellow
https://l.ctrl-felix.de/FbUuL

**Comment by CommunityStaking** [comment]
Please still make sure this has been settled before distribution of the delegation.

> Hello Hathor Node, please make sure you have the prerequisites of the delegation program covered asap or you will lose the BitSong delegation. In regards to the Commission restake we ask what you will commit during the epoch (3 months, starting 1 June 2022).

**Comment by Pharaon1993** [comment]
My apologies, this was in my spam mail. Will read over the thread and try to correct what's missing!

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
