### ISSUE TITLE
Stakewolle.com

### ISSUE THREAD

**Issue by Clarxxon** [bitsongofficial/delegation-program#28]
### Validator address

bitsongvaloper1pn6mhrwq8vdhns366jwxkggmhmxypuhrrc4huu

### On Chain Data

- [X] I confirm to have set my validator information on chain

### Contact information

https://t.me/clarxxon Islam | Stakewolle.com#3955

### Application categories

Uptime, Commission restake, Participation in the BitSong ecosystem, None core development, Running relayers, Running an archive node, Running an public rpc/api

### Details

we can provide our services for writing various monitoring bots, server facilities for providing archive and public nodes, we also have a very strong promotion team. We shoot regular news releases (YouTube https://www.youtube.com/channel/UCwlJ1gUZOLw_nEZddngnrbQ).

### Goals

our priority is to help the crypto community grow! We help the community both with development and in the information space!

### Timetable

we release videos at least 2 weeks apart and make special releases with guides as soon as a new interesting event appears! Until the end of the year, we are finalizing our public dashboard with сcosmos-network monitoring

**Comment by ctrl-Felix** [comment]
Hi, thank you very much for your application. May I ask you what target ratio you want to achieve with the comission restaking?

**Comment by Clarxxon** [comment]
Good day! the target commission of our validator is 5%

вт, 17 мая 2022 г., 22:42 Felix ***@***.***>:

**Comment by ctrl-Felix** [comment]
Thanks for the answer. However, it's not what I meant. Can you maybe provide the ratio you want to restake of the comission?

**Comment by Clarxxon** [comment]
we plan to spend no more than 20% of the commission on paying for servers.
Everything else will be restake

ср, 18 мая 2022 г. в 10:13, Felix ***@***.***>:

**Comment by TheCrazyStaker** [comment]
Hello Stakewolle.com
We assumed that you will restake 80% of your profit (as you stated in the post above). Your node/rpc/api scoring will be zero because you didn't provide any link to this so we assumed you didn't set them up yet. 
You have 1540 points, link bellow:
https://l.ctrl-felix.de/NQDfB
