### ISSUE TITLE
TdrSys application

### ISSUE THREAD

**Issue by t3d3r3** [bitsongofficial/delegation-program#29]
### Validator address

bitsongvaloper1wqcqfm499f84cjnppqu03jrkqtwqsndpw9qxc5

### On Chain Data

- [X] I confirm to have set my validator information on chain

### Contact information

discord:tdr#4877/telegram:@MihaiTdr/mihaitdr@gmail.com

### Application categories

Uptime, Commission restake, Self delegation, Running an public rpc/api

### Details

I like the project and will support any way i can. Besides running a validator node i can also set up a public RPC node.
All profits will go to stake.

### Goals

Cover the hardware costs and stake profits.

### Timetable

A couple of days to set up the RPC node.

**Comment by ctrl-Felix** [comment]
Hi, thank you very much for your application. May I ask you what target ratio you want to achieve with the comission restaking? You said all the profits which means you probably want to pay your costs with the comission which is legitimate. But can you maybe try to estimate how much you will restake and which part you need?

Furthermore, do you plan to get your rpc nodes up before the 1st June?

**Comment by t3d3r3** [comment]
Hi @ctrl-Felix , that is my long term goal. I will keep restaking 100% at least until the next delegation round. Right now i cannot estimate not knowing how much stake i will get, plus i am considering lowering the commission. 

RPC will be up by June 1st.

**Comment by t3d3r3** [comment]
Hi again @ctrl-Felix, rpc is up: bitsong.tdrsys.com:25631

**Comment by CommunityStaking** [comment]
Score: 2070
https://l.ctrl-felix.de/4145P

**Comment by ctrl-Felix** [comment]
> Hi again @ctrl-Felix, rpc is up: bitsong.tdrsys.com

Hi, is this still working?

**Comment by t3d3r3** [comment]
Hi @ctrl-Felix,

Yes, still up:
RPC: ```curl https://bitsong.tdrsys.com/node_info```
LCD: ```curl https://bitsong.tdrsys.com:2053/status```
