### ISSUE TITLE
kytzu.com

### ISSUE THREAD

**Issue by bogdanavram** [bitsongofficial/delegation-program#30]
### Validator address

bitsongvaloper1xe4et8cypskz6xggqa0ahgsnpqg7ac8dt52mgy

### On Chain Data

- [X] I confirm to have set my validator information on chain

### Contact information

Kytzu#4371/@Kytzu/calin.chitu@gmail.com

### Application categories

Uptime, Commission restake, Self delegation, Running an public rpc/api

### Details

The project looks very intersting to me, I do my best to support it.
For the moment I run and monitor a Bitsong validator node zith focus on uptime,
The profits are redelegated to the node.
For more info https://kytzu.com/ 

### Goals

The next step will be the setting up a public RPC node and relayers.

**Comment by ctrl-Felix** [comment]
Hi, thank you very much for your application. May I ask you what target ratio you want to achieve with the comission restaking?

**Comment by bogdanavram** [comment]
Hi, kytzu bitsong node is already up and runing since the genesis. At least 50% of the reward will be staked. Reagarding the RPC/relayer this will be done in best effort but for the moment I can't communicate a date.

**Comment by CommunityStaking** [comment]
Hello kytzu, please make sure you have the prerequisites of the delegation program covered asap or you will lose the BitSong delegation.

**Comment by CommunityStaking** [comment]
Score: 616
https://l.ctrl-felix.de/zZfrM

Note: Prerequisites of the delegation program hasn't been met yet. Please do so ASAP

**Comment by ctrl-Felix** [comment]
Please set your logo (mintscan & big dipper) and a website on chain

**Comment by ctrl-Felix** [comment]
Can you provide the links to the public nodes please
