### ISSUE TITLE
Noderunners

### ISSUE THREAD

**Issue by rewseRE** [bitsongofficial/delegation-program#31]
### Validator address

bitsongvaloper12xtuwyt599dv57y7v007qpp230ph3utkssnx7n

### On Chain Data

- [X] I confirm to have set my validator information on chain

### Contact information

rewse#4063/rewse/info@noderunners.biz

### Application categories

Uptime, Commission restake, Self delegation, Participation in the BitSong ecosystem

### Details

Noderunners is a Bitsong genesis validator. We are took part in all testnets and programs of the ecosystem. We restaked all rewards and commissions from the start of the network.
Noderunners - mainnet validator and active participant of the other 14 Cosmos SDK based blockchains.

**Comment by ctrl-Felix** [comment]
Hi, thank you very much for your application. May I ask you what target ratio you want to achieve with the comission restaking?

**Comment by rewseRE** [comment]
100% restaking for this market situation.
