### ISSUE TITLE
Validatrium application

### ISSUE THREAD

**Issue by Validatrium** [bitsongofficial/delegation-program#32]
### Validator address

bitsongvaloper10fg3yklae97g8ueh5ut29mlwz8fdr6z8zrak6x

### On Chain Data

- [X] I confirm to have set my validator information on chain

### Contact information

validatrium.com ; t.me/validatrium ; t.me/Igor_Validatrium ; https://twitter.com/validatrium ; info@validatrium.com

### Application categories

Commission restake, Self delegation, Participation in the BitSong ecosystem, Running relayers, Running an archive node, Running an public rpc/api

### Details

Hello everyone, my name is Igor, I'm community manager team lead at Validatrium.com
Igor (community manager): [validatrium] Igor#8102
Yuri (tech manager): [validatrium] Yuri Tech#0264

Over past two years we have set up 80+ nodes in 45+ networks, including ETH 2.0, Hydra, Kava, Polkdadex, Oasis, Kusama, Velas, BitSong, Centrifuge, Axelar, Evmos, Forta, Clover, Ki Chain, Umbrella, Sifchain, Lum, Near, Kava, etc., with fair rates and continued support to the community.

Our community channels
Telegram: https://t.me/validatrium
Twitter: https://twitter.com/validatrium
LinkedIn: https://www.linkedin.com/company/validatrium/

We have techteam members assigned to the project to maintain the highest uptime and quickly solve incidents, requests, etc.
Besides we help creating technical tutorials for projects we participate (we have created step-by-step non-tech tutorial to ease the process of participation in Sinfonia testnet. once we will get access to new testnet as a validator, we will create tech tutorial on node-running)

**Uptime**
- Mainnet node uptime: 100% (https://www.mintscan.io/bitsong/validators/bitsongvaloper10fg3yklae97g8ueh5ut29mlwz8fdr6z8zrak6x)
- Testnet node uptime: 100% (we had 100% of voting power, Angelo might confirm this)

**Commission restake:** we plan to restake 60% of our reward on a daily basis

**Self delegation:** we have bought and delegated to our node 13999 BTSG tokens (first transactions), let me know if you need proofs. we use different accounts due to security reasons.

**Participation in BitSong ecosystem**
- participate in governance (missed one proposal due to the fact that we have registered our validator and were buying tokens for self stack, once tokens were delegated - we saw that we missed proposal)
- took part in creating Delegation DAO
- created non-technical tutorial for members to know how to participate in Sinfonia Testnet - https://telegra.ph/How-to-create-BitSong-wallet-and-participate-in-Sinfonia-Testnet-05-11
- run non-incentivized testnet to support project voluntarily (had 100% of voting power and solely supported testnet for a few months)

**Running relayers:**
Running relayer node (Osmosis-BitSong):
- Bitsong relay account address: bitsong1ku7u5axp3rpyk6kky02j9v5rp0j98v8ymzku35
- Osmosis relay account address: osmo1kqan6njymshfem9srxea09v3wzhly83ws64dxw

**Running rpc/api:**
Running rpc/api: https://bitsong-rpc.validatrium.club/ ; https://bitsong-api.validatrium.club/

**Running archive node:**
Running archive node (peer ID): 5b40df19ef20889f2ad3dfe6a1c7b43b94d1d1f9@78.47.80.108:13256
Node is still syncing (3980365/5985992)

**Additional**
We spread a word about BitSong milestones with our community via telegram, twitter and linkedin.

### Goals

**Goal** - long-term participation in the project, taking active governance part, creating tutorials and continuous support of the community. We dedicate community manager and technical manager to work with BitSong and support community with best we can.

**What else do we provide?**
Validatrium takes part to benefit each project we are working with, we tend to create different tutorials to support community with a step-by-step solutions on running nodes, creating wallets, using faucets, staking, setting up node health check notifications, etc.
Depending on the project, our team is always trying to find the best solution to engage community and create something special to ease process of joining the project and developing it.
Team is always ready to answer questions via discord, telegram, twitter, etc.
Validatrium has it's own community channels, where we promote projects, share tutorials, and let our community know about any critical updates and contests.

### Timetable

contribution:
- we helped supporting testnet (had 100% voting power, provided public RPC to Angelo), waiting for invitation to run a node in testnet and support network as we previously did
- create non-technical tutorial for members to know how to participate in Sinfonia Testnet - https://telegra.ph/How-to-create-BitSong-wallet-and-participate-in-Sinfonia-Testnet-05-11
- participated in Delegation DAO document creation
- continue spreading the word about BitSong milestones on a permanent basis

**Comment by ctrl-Felix** [comment]
Thank you very much for your application!
Am I right that the provided api/rpc not a archive node is?

**Comment by Validatrium** [comment]
Hello Felix,
thanks for getting back to me!

These are separate nodes
Both RPC and API are synced and ready
Archive node is still syncing (for 1 week already, current status: 4073221/6000384)

let me know if you have any additional questions

**Comment by TheCrazyStaker** [comment]
Dear Validatrium,
According to our calculation, you got a very good scoring of 4375 points.
Congratulations and thank your for contributing to our ecosystem. Link bellow:
https://l.ctrl-felix.de/rmsjx

**Comment by Validatrium** [comment]
Dear @TheCrazyStaker and BitSong Team, thank you!
Pleasure being part of this awesome project!

**Comment by ctrl-Felix** [comment]
> Dear @TheCrazyStaker and BitSong Team, thank you! Pleasure being part of this awesome project!

bitsong1ku7u5axp3rpyk6kky02j9v5rp0j98v8ymzku35

Can you please restart your relayer? It seems to be down for 18 days now. If it's not restarted before we do the delegations I'll unfortunately have to remove those points

**Comment by TheCrazyStaker** [comment]
new calculations https://l.ctrl-felix.de/7hpWr
new scoring: 4250 pts

**Comment by ctrl-Felix** [comment]
We are using a adjusted ranking without foundation delegations (https://bitsong.ctrl-felix.de/validators -> Press Switch to adjusted) to see the ranking how the community is ranking the validators

**Comment by Validatrium** [comment]
@ctrl-Felix please check our relayer
problem was caused by Osmosis, as network was down
