### ISSUE TITLE
dimi 🦙

### ISSUE THREAD

**Issue by dimiandre** [bitsongofficial/delegation-program#33]
### Validator address

bitsongvaloper1dmmupr5qqy07sksct3au8tx9vuh224vg53fl6x

### On Chain Data

- [X] I confirm to have set my validator information on chain

### Contact information

dimiandre

### Application categories

Uptime, Commission restake, Self delegation, Participation in the BitSong ecosystem, Core development

### Details

Support Bitsong initiatives across the cosmos ecosystem with focus on Juno synergies
Code reviews

**Comment by ctrl-Felix** [comment]
Hi, thank you very much for your application. May I ask you what target ratio you want to achieve with the comission restaking?

**Comment by CommunityStaking** [comment]
Hello dimi, please make sure you have the prerequisites of the delegation program covered asap or you will lose the BitSong delegation. We also still need to know what percentage you are committing to restake from the commission if you want to continue to apply for this category.

**Comment by TheCrazyStaker** [comment]
Hello dimi,
According to our calculations, you are getting 116 points, link here: https://l.ctrl-felix.de/wSGUX
You didn't specify RPC nodes/relayers, neither your intention regarding commission restaking so we assumed 40% and proceeded.

**Comment by TheCrazyStaker** [comment]
New corrected calculations: https://l.ctrl-felix.de/sEXHm
New scoring: 99 pts
