### ISSUE TITLE
ITA Stakers Application

### ISSUE THREAD

**Issue by itastakers-devs** [bitsongofficial/delegation-program#34]
### Validator address

bitsongvaloper1fkj2cn209yeexxyets98evrcmmds23hck0lyzq

### On Chain Data

- [X] I confirm to have set my validator information on chain

### Contact information

itastakers.com/zaketac | ITA Stakers#2307/@zaketac/itastakers@gmail.com

### Application categories

Uptime, Commission restake, Self delegation, Participation in the BitSong ecosystem, Running an archive node, Running an public rpc/api

### Details

We are a group of experienced Italian developers and sys admins, who are making their way into the cosmos ecosystem bottom up. As of today we are active as Validator on many of the Cosmos chains, to mention some: Juno, Osmosis, Sentinel, BitSong, Desmos, Crescent, Cosmos, Lum. For us validating is not only "run and forget", but we always try as our best contributing to the project in many ways. 

### Goals

https://rpc-bitsong.itastakers.com
https://rpc-bitsong-archive.itastakers.com
https://quickstake.itastakers.com

### Timetable

long term support to the project from 2019

**Comment by ctrl-Felix** [comment]
Hi, thank you very much for your application. May I ask you what target you want to achieve with your comission restaking?

**Comment by TheCrazyStaker** [comment]
Hello, itastakers-devs, you got 193 points, the calculation is here: https://l.ctrl-felix.de/nFUaY
You didn't specify your intention regarding commission restaking so we assumed 40% and proceeded.
