### ISSUE TITLE
Nodtech application 

### ISSUE THREAD

**Issue by nodtechee** [bitsongofficial/delegation-program#35]
### Validator address

bitsongvaloper1aakd7kru6n9l2ty565j3t893ygadc9xz0c65mk

### On Chain Data

- [X] I confirm to have set my validator information on chain

### Contact information

https://nodtech.eu/  , @zVOLz

### Application categories

Uptime, Commission restake, Self delegation, Participation in the BitSong ecosystem

### Details

Professional validators. Supported Bitsong from first testnet. Fast upgrades and good reaction.
Website https://nodtech.eu/
Twitter https://twitter.com/nodtecheu
Telegram https://t.me/nodtechee

### Goals

Goals long-term participation in the project,  active governance, spred info about Bitsong, create content , and support in social media!

**Comment by ctrl-Felix** [comment]
Hi, thank you very much for your application. May I ask what your comission restaking target is?

**Comment by nodtechee** [comment]
> Hi, thank you very much for your application. May I ask what your comission restaking target is?

Hello Felix
100% of the commission will be restaked .
Regards

**Comment by CommunityStaking** [comment]
Hello nodtech, please make sure you have the prerequisites of the delegation program covered asap or you will lose the BitSong delegation.

**Comment by nodtechee** [comment]
> Hello nodtech, please make sure you have the prerequisites of the delegation program covered asap or you will lose the BitSong delegation.

Basic information was set on chain .
Regards

**Comment by CommunityStaking** [comment]
Not seeing any logo here: https://www.mintscan.io/bitsong/validators/bitsongvaloper1aakd7kru6n9l2ty565j3t893ygadc9xz0c65mk

**Comment by nodtechee** [comment]
PR created

**Comment by freak12techno** [comment]
@ctrl-Felix if my calculations are correct, it's 1437 points: https://l.ctrl-felix.de/bLTIf
