### ISSUE TITLE
Application

### ISSUE THREAD

**Issue by landyk** [bitsongofficial/delegation-program#36]
### Validator address

bitsongvaloper1dthr54nysxnltnaxk4nmx2udqvlst8e5qh2yzw

### On Chain Data

- [X] I confirm to have set my validator information on chain

### Contact information

@fippy 

### Application categories

Uptime, Commission restake, Self delegation, Participation in the BitSong ecosystem

### Details

I joined Bitsong validators from testnet.  Still node is running and i support team and community.

**Comment by ctrl-Felix** [comment]
Hi, please ensure you have set your validator information on chain (logo and website is missing)

**Comment by landyk** [comment]
Added ty

**Comment by landyk** [comment]
80%+ will be restaked

**Comment by CommunityStaking** [comment]
Hello lana, please make sure you have the prerequisites of the delegation program covered asap or you will lose the BitSong delegation. I see no logo or contact information still...

**Comment by landyk** [comment]
Info added ty

> Hello lana, please make sure you have the prerequisites of the delegation program covered asap or you will lose the BitSong delegation. I see no logo or contact information still...

**Comment by CommunityStaking** [comment]
Are you sure? I see no logo and no logo nor do I see it requested on cosmostation github.
