### ISSUE TITLE
Roal delegation

### ISSUE THREAD

**Issue by Roalkege** [bitsongofficial/delegation-program#37]
### Validator address

bitsongvaloper1h6a9l0ssh4n9lqgcfanqf7702k3980gl7jyx6c

### On Chain Data

- [X] I confirm to have set my validator information on chain

### Contact information

Telegram: @roalkege

### Application categories

Uptime, Commission restake, Self delegation

### Details

No additional information.

**Comment by CommunityStaking** [comment]
Great, and your logo is still being added?

**Comment by Roalkege** [comment]
I used Keybase to add the Image.
https://explorebitsong.com/validators/bitsongvaloper1h6a9l0ssh4n9lqgcfanqf7702k3980gl7jyx6c

**Comment by freak12techno** [comment]
@ctrl-Felix if my calculations are correct, it's 1600 without contributions: https://l.ctrl-felix.de/4gxNd
