### ISSUE TITLE
Rundax validator

### ISSUE THREAD

**Issue by Hantok** [bitsongofficial/delegation-program#38]
### Validator address

bitsongvaloper1wtf99e8l5k2yxxc0rj6xwxj7mfam9hfnjqznja

### On Chain Data

- [X] I confirm to have set my validator information on chain

### Contact information

roman@rundax.com, https://t.me/hantok

### Application categories

Uptime, Commission restake, Self delegation, Participation in the BitSong ecosystem, None core development

### Details

Rundax is a Bitsong genesis validator.
Created and support the Ukrainian/Russian language group in telegram https://t.me/bitsongru
Created Docker container for Bitsong node https://github.com/rundax/bitsong

### Goals

High uptime. Spread in the artists' communities. 
At least 50% or more rewards are re-staked.

### Timetable

Since the first Bitsong Testnets and Genesys mainnet

**Comment by ctrl-Felix** [comment]
Unfortunately you didn't vote on the last governance proposal which was mandatory to get the required governance participation score. Therefore you won't be eligible for this delegation period. There will be new proposals before the second period so that you can participate there if you vote.
