### ISSUE TITLE
bitsong91

### ISSUE THREAD

**Issue by huynhvanquy91** [bitsongofficial/delegation-program#39]
### Validator address

bitsong19z7t9y230ltxay9jdu5rhuw52qdxs7jmg7fd6f

### On Chain Data

- [X] I confirm to have set my validator information on chain

### Contact information

huynhvanquy91@gmail.com

### Application categories

Participation in the BitSong ecosystem

### Details

bitsong19z7t9y230ltxay9jdu5rhuw52qdxs7jmg7fd6f

**Comment by ctrl-Felix** [comment]
Hi! Thank you for your application. However, this delegation program is for validators and not for delegators and that's why you aren't eligible...
