### ISSUE TITLE
Safe Block

### ISSUE THREAD

**Issue by SafeBlockSpace** [bitsongofficial/delegation-program#40]
### Validator address

bitsongvaloper1fgmzy5rtvvnxzy0vn54mz9k5xndzt2afepyye3

### On Chain Data

- [X] I confirm to have set my validator information on chain

### Contact information

DISCORD: Francesco | SafeBlock #0323 ; TELEGRAM: @frenkrina ; EMAIL: support@safeblock.space

### Application categories

Uptime, None core development

### Details

Good evening, my name is Francesco, I have been serving the SafeBlock Validator on the Bitsong mainnet network since March 2022. We have voted on the Governance proposal that has been presented and we are uptime.

Linktr.ee: https://linktr.ee/safeblock.space

Contact: 
E_mail: support@safeblock.space
Telegram: @Frenkrina
Discord: Francesco | Safe Block #0323

### Goals

Our goal is to keep the node uptime in the best possible way to avoid creating losses for investors and to transmit security and trust. We are organizing to create content on our social profiles such as articles and tutorials to bring Bitsong to the attention of fans and music artists.

We are testing private key signing on a separate host and will be enabling the restake shortly.
At the moment do not currently supply rpc but we will be working on this in the next few months to come.

We will only cover the running costs and all the rest will be delegated for greater long-term profit.

Greetings

Francesco

**Comment by SafeBlockSpace** [comment]
For Restake Commission:
We not have currently withdrawn any fees since we started signing blocks.
We will make a wallet in these days that we will use to replay the commissions (we will not use the validator wallet for security reasons). When Bitsong becomes profitable, we will consider a small sales allocation to pay for the validating machines. We cannot sell our commissions for the moment.

Francesco

**Comment by ctrl-Felix** [comment]
Score: 1404
https://l.ctrl-felix.de/AomKN

Thank you very much for your submission
