### ISSUE TITLE
Application from validator "Coding Everyday | 打碼大聯盟"

### ISSUE THREAD

**Issue by gcake119** [bitsongofficial/delegation-program#42]
### Validator address

bitsongvaloper100akrazwzrxhklgnh2ueaqfcv7kcanh9ew3jxf

### On Chain Data

- [X] I confirm to have set my validator information on chain

### Contact information

Discord_Erica#2697

### Application categories

Uptime, Commission restake, Self delegation, Participation in the BitSong ecosystem

### Details

Uptime - retain at >99%; 
Commission restake - The restake is 80% for the first three months. We would like to re-estimate the cost of maintaining the server these days. Even the commission cannot cover the server cost, the restake would not be below 70%; 
Self delegation - Buy BTSG using our own fund in case the price is relatively low, the amount is about 2000 BTSG until now;  
Participation in the BitSong ecosystem - Wrote articles introduce the main function and campaign on chain for Chinese-speaking Community

Some articles listed as below (All in Chinese):
[Fantoken Airdrop information](https://matters.news/@erica072/259942)
[News about Sinfonia platform](https://liker.social/web/@erica072/108258698177435357)
[Promotion meme for delegators](https://liker.social/web/@erica072/107915578782098292)

### Goals

Our team goal is to spread the blockchain and crypto ecosystem to the chinese-speaking community. 
NFT tutorial online workshop and blockchain online seminar would be held in Q3.

**Comment by erica-liu-072** [comment]
Restake commission: 80%
The current commission is not enough to cover the servers rent.

**Comment by freak12techno** [comment]
@ctrl-Felix if I evaluated this correctly, the final score is 1725 not including the contributions: https://l.ctrl-felix.de/FO9bh

**Comment by erica-liu-072** [comment]
> Can you please add your logo to mintscan asap 

Done
https://www.mintscan.io/bitsong/validators/bitsongvaloper100akrazwzrxhklgnh2ueaqfcv7kcanh9ew3jxf
