### ISSUE TITLE
coldy validator

### ISSUE THREAD

**Issue by doggystylez** [bitsongofficial/delegation-program#43]
### Validator address

bitsongvaloper1wq3hjdygz9n84z826p56zft0e45kmlfrnsy4p4

### On Chain Data

- [x] I confirm to have set my validator information on chain

### Contact information

discord coldchain#6999

### Application categories

Uptime, Commission restake, Self delegation, Running relayers

### Details

relayer addresses:
bitsong1c3cy3wzzz3698ypklvh7shksvmefj69xmj4dq9
cosmos1c3cy3wzzz3698ypklvh7shksvmefj69xhm89z2
osmo1c3cy3wzzz3698ypklvh7shksvmefj69xlq545c

### Goals

securing the Bitsong network and keeping IBC running smoothly

**Comment by doggystylez** [comment]
restaking 100% for foreseeable future

**Comment by CommunityStaking** [comment]
Hello coldy, please make sure you have the prerequisites of the delegation program covered asap or you will lose the BitSong delegation.
