### ISSUE TITLE
Chainode Tech Validator Application

### ISSUE THREAD

**Issue by Chainode** [bitsongofficial/delegation-program#44]
### Validator address

bitsongvaloper1403j638u8jtyu9zyhcc9p0cl596y63u75vnkj0

### On Chain Data

- [X] I confirm to have set my validator information on chain

### Contact information

Ionut S. | Chainode Tech#8971/@iscirlet/ionut@chainode.tech

### Application categories

Uptime, Commission restake, Self delegation, Participation in the BitSong ecosystem, None core development

### Details

We are a professional institutional-grade Web 3.0 infrastructure and service provider, which takes validator responsabilities seriously and has supported Bitsong since early testnet phases. 

We have a relatively high amount of self-delegated BTSG tokens and we have re-staked all the rewards from our commission as well as from our own self-delegation. 
We are also actively participating in all network events that are relevant and critical for the health and well-being of the Bitsong network like important governance as well as upgrade events.

### Goals

We will continue to have a professional behaviour and support the Bitsong Network at least for as long as we will be a Validator in the network. Also, through our high self-stake and re-stake of BTSG tokens we clearly display our interest in the well-being of the network as well as our high commitment to it. 

At the same time, we plan to release a similar Bitsong Toolsuite for Monitoring the validators, the network and the underlying hardware as we did for another Cosmos chain (Agoric) - reference: https://github.com/Chainode/AgoricTools

### Timetable

Continously and the Bitsong Toolsuite for Monitoring is planned to be released in the next 3-4 months.

**Comment by ctrl-Felix** [comment]
Score: 1014
https://l.ctrl-felix.de/vnUaX

Thank you for your application and participation. I am looking forward to your Toolsuite!
