### ISSUE TITLE
Enigma Validator

### ISSUE THREAD

**Issue by Enigma-Validator** [bitsongofficial/delegation-program#45]
### Validator address

bitsongvaloper1n05tgtv6pyr8ymp6g7f3wceutktv2xfzmkkqmf

### On Chain Data

- [X] I confirm to have set my validator information on chain

### Contact information

Enigma#6403/enigma_validator/enigma.validator@gmail.com

### Application categories

Uptime, Self delegation, Participation in the BitSong ecosystem, None core development

### Details

Enigma is running a validator on the Bitsong mainnet since more than 6 month (end of December) and we are constantly uptime (100%).
We have often work with the team in order to develops tools, share with our community information about Bitsong and bring help to the community. 
Until now we have:
- Keep running our validator (100% Uptime) and voted on the Governance proposal
- Build and develop the discord chatbot  (that is currently in development in order to improve it)
- Build and develop the Bitsong price bot in order to retrieve and print:
              1. BTSG price evolution
              2. Market cap
              3. APR
              4. Circulating Supply
              5. Total Supply

- Organised a giveaway for the Bitsong community and we make communication on the project to bring more interest
- Participate as often as we can to the discord server to help the community

### Goals

Our goals are

- Keep securising the network by running our validator uptime and participate to the governance proposal
- Building more tools that will help the project and the community (more tools are in development and we be presented in the month to comes)
- Bring more interest to the Bitsong project
- Setup relayers services if needed

**Comment by ctrl-Felix** [comment]
Score: 387
https://l.ctrl-felix.de/JWezE

Do you restake comission? I used the default value of 40% for the calculation but you didn't apply for that category. If you restake, what is the ratio of coins you restake?
