### ISSUE TITLE
BadgerBite Application

### ISSUE THREAD

**Issue by Thor-BadgerBite** [bitsongofficial/delegation-program#47]
### Validator address

bitsongvaloper125ph4snec4yneqagk5u07e95sej4zhjcjw3yx9

### On Chain Data

- [X] I confirm to have set my validator information on chain

### Contact information

Thοr#8826 - https://t.me/BadgerbiteValidator - badgerbiteit@gmail.com

### Application categories

Uptime, Commission restake, Self delegation, Participation in the BitSong ecosystem

### Details

We are a new union of experienced Validators currently spreading among mainy chains...mainly in Cosmos Exosystem as well as EOSIO.
Our team consists of crypto enthousiasts who share the same vision of **crypto decentralization**
We are in proccess of creating our DAO LLC union as well as securing investors in crypto space
Participation and engagement is our primary focus in every chain we take part of as well as helping the community regarding technical matters and promoting decentralization
Taking Governance seriously we help secure every network with take part in with responsible voting and proposal

For more info please visit badgerbite.info

Bitsong is one of the first network we participated since BadgerBite formation at the beginning of the year
During this time we stayed and we plan to stay true to our principals

- hosting in enterprise grade datacenters with a plan to migrate to our own private datacenter in near future
- ensuring highest uptime possible with 24/monitoring and alerting systems
- continue to grow,innovate and adapt to new tech
- providing assistance to all who need with our tech expertise
- working with developers on ideas and proposals who secure and decentralize further

### Goals

Regarding our goals we also stay true to our philosophy and long-term approach which includes

- continue to provide a secure stable validation with highest uptime possible
- provide tech assistance in solving problems at times of crisis
- promoting Bitsong through our social channels and why not try to introduce and onboard new artists in Bitsong Ecosystem
- Represent our delegators in responsible and mature voting procedures
- Keeping a low threshold of fees covering only server costs and redelegating to our node on periodic basis

### Timetable

After our DAO LLC is formed we are planning to raise our self stake with a substantial amount from our treasury
We also plan mifrating to our local private datacenter ensuring security even further

We may me a fairly new Organization but we plan to stay for a very lobg time

Thank you for taking the time to read and review our application,for any inquiries or even a meet up we ll be more than happy to assist!

Best regards,
BadgerBite

**Comment by ctrl-Felix** [comment]
Hi, please set your website on chain and make the pull request to get your logo onto mintscan.

**Comment by ctrl-Felix** [comment]
Unfortunately I just noticed that you didn't vote on the last governance proposal. The proposal is mandatory to be eligible for a delegation. There will be further proposals before the next epoch to vote on to get a delegation then.
