### ISSUE TITLE
qf3l3k application

### ISSUE THREAD

**Issue by qf3l3k** [bitsongofficial/delegation-program#48]
### Validator address

bitsongvaloper1x2slrjfmgxq7qx3xwmsjue73t5ynmwy7jgpdtr

### On Chain Data

- [X] I confirm to have set my validator information on chain

### Contact information

Discord: qf3l3k#0603
Telegram: https://t.me/qf3l3k
Website: https://qf3l3k.tech
Email: contact@qf3l3k.tech
Email2: qf3l3k@gmail.com

### Application categories

Uptime, Commission restake, Self delegation, Participation in the BitSong ecosystem, Running relayers, Running an public rpc/api

### Details

**Uptime** - for main validator I keep up to date backup ready at all times to take over the role. 

**RPC** - providing public RPC endpoint at the moment available at [Bitsong RPC](https://rpc.bitsong.chaintools.tech:443)
**API** - providing public API endpoint at the moment avialable ar [Bitsong API](https://api.bitsong.chaintools.tech:443)

**Relayer** - at the moment running relayer services for 3 other chains. Want to include Bitsong in June/July.

**Self delegation** - at the moment I delegated 16k $BTSG to my validator through 2 different wallets. Going forward planning to increase this amount.

**Commission restake** - for first 3 months I'd like to restake 100% of commission, after 3 months do checkpoint and re-evaluate that, if reward is enough to maintain infrastructure.

**Participating in Bitsong ecosystem** - as I'm mostly on infrastructure side of technology, I'm definitely up for running testnets, evaluating new releases, providing infrastructure to run web-apps, when needed. Also, happy to help with technical things, which happen to be for statesync and IBC testing and relaying during one of testnets. Along that I also run instance of ping explorer with Bitsong chain available published [here](https://explorer.chaintools.tech).

### Goals

For a long term run I'd like to help around infrastructure for nodes and validators in form of contributing to testnets and evaluations, documentation. Considering specific of the projects, which is more media orientated, might be good idea to do some interactive Q&A sessions or video tutorials. This is something which I will be happy to work on with project team, other validators perhaps stakers.

### Timetable

In terms of timing, like I mentioned earlier:
**Relayer** - will be activated June/July 2022

**Comment by ctrl-Felix** [comment]
Score: 1179
https://l.ctrl-felix.de/pic47

Thank you for your participation
Could you maybe share your second address you delegate funds from?

**Comment by qf3l3k** [comment]
Absolutely. 
I list all addresses here as now there are 3:

- bitsong1x2slrjfmgxq7qx3xwmsjue73t5ynmwy7nvaym7 - Validator main address
- bitsong1zgqfays0vrgy900dvh4hwauqw43ttsm2e5ufzs - Delegation 1
- bitsong1wfdkvf5qywhr6ky6srmcldy0j5adxshep4l0c5 - Delegation 2 - this is also withdrawal address for all rewards. I plan to withdraw all to this address and re-delegate to validator from this address, if this is fine.

**Comment by qf3l3k** [comment]
Also, in the meantime total self-stake went from 16k to 22k.

**Comment by ctrl-Felix** [comment]
Thank you for the update!
Your new Score then is: https://l.ctrl-felix.de/OaxVL

**Comment by qf3l3k** [comment]
StateSync service is running now... it is also fully documented:
https://docs.chaintools.tech/chains/chain-services/statsync/bitsong

**Comment by angelorc** [comment]
Very useful. I added it into our documentation some months ago

**Comment by qf3l3k** [comment]
gRPC UI for BitSong chain: https://bitsong.grpcui.chaintools.host/
This is based on Web UI we found and hooked up to BitSong.
Might be very useful to quickly query chain actually.

**Comment by angelorc** [comment]
Yes, grpcui is very useful. We should add all the resource into our docs
