### ISSUE TITLE
CosmosDrops

### ISSUE THREAD

**Issue by bladeruner** [bitsongofficial/delegation-program#49]
### Validator address

bitsongvaloper1qyc9ccfx7clj0kswgjz6cdf5f4n6v4nyeudy8q

### On Chain Data

- [X] I confirm to have set my validator information on chain

### Contact information

Kirill 2zMoon#3200 / @antiborsh

### Application categories

Uptime, Commission restake, Self delegation, Participation in the BitSong ecosystem

### Details

Individual validator, active member and moderator of Cosmos based chains communities. I plan to restake 100% of commissions.

### Goals

Active governance participation. Maintain high uptime, restake rewards and commissions to increase self-delegation.
I want to become part of the bitsong ecosystem, provide active support to users and translate and create content about Bitsong.

**Comment by ctrl-Felix** [comment]
Score: 1825
https://l.ctrl-felix.de/Y0O1T

Thank you for your application
