### ISSUE TITLE
TravazStake Delegation DAO | application

### ISSUE THREAD

**Issue by travazstake** [bitsongofficial/delegation-program#50]
### Validator address

bitsongvaloper1laj23uelt20tp37y9r6mt6mtzktn73cqmsl35q

### On Chain Data

- [X] I confirm to have set my validator information on chain

### Contact information

Discord: Travaz | TravazStake

### Application categories

Uptime, Commission restake, Self delegation, Participation in the BitSong ecosystem

### Details

I have been an early bird in supporting the ecosystem from the announcement and later participation of the BitSong ICO back in 2018. The project outlined in the whitepaper is incredibly valid. Since the ICO I have seen the tremendous development of the ecosystem and the original vision starting to become a reality. At the beginning of this year, I decided to increase my commitment to the project by stepping into the game and becoming a validator with solid uptime and full self-delegation and commission restacking. I would like to continue on this path and pursue the goals I will outline in the next paragraph to continue contributing to the growth of the ecosystem.

**Uptime**: more than 98%

**Commission restake**: so far all the commissions coming from the node have been re-staked to contribute in increasing the network security. No plans have been made to sell the tokens and won't be made in the near future.

**Self restake**: the restaking constists of 100% for our self-staking mechanism. These are rewards coming from the re-staking process happening on the node. Hence, both the rewards from staking and well as the validators commission are currently being re-invested in the network to make is secure.

**Participation in the BitSong ecosystem**: as a validator the partecipation and contribution process carried on so far was mainly related to on-board friends to the ecosystem and allow them to play with the testnet. On this regards, the [Medium page](https://medium.com/@dtravaz) Medium page of the validator has a guideline that explain in details how to enter in the BitSong ecosystem for people that approach crypto for the very first time. The plan is to extend this guideline to make people more comfortable with crypto and in general to increase awareness of the crypto-space

### Goals

I have recently convinced some of my friends to try out the Sinfonia testnet and I received tremendous feedback from them on how intuitive (with little explanation on the purpose of such a project and platform) it was to use.
Hence, my goal would be to expand this call to many and many more friends, supporting them with articles that explain the reason for jump-starting their journey into the ecosystem and writing how-to guides on how to quickly support artists all around the globe.

### Timetable

The goals outlined above should be made concrete by the end of this year.

**Comment by travazstake** [comment]
@ctrl-Felix updated the application with the restaking information as required.

**Comment by CommunityStaking** [comment]
Hello TravazStake, please make sure you have the prerequisites of the delegation program covered asap or you will lose the BitSong delegation.

**Comment by travazstake** [comment]
Hi @CommunityStaking, I thought I covered all of them with the last update on the issue including the restake update. Do you see any other prerequisite missing?

**Comment by travazstake** [comment]
A pull request was made where the icon is up and loaded into the repository.
https://github.com/cosmostation/cosmostation_token_resource/pull/2246

**Comment by ctrl-Felix** [comment]
Score: 280
https://l.ctrl-felix.de/dfIB7

Thank you very much for your participation and long time commitment
