### ISSUE TITLE
Thamar DAO Applicaton

### ISSUE THREAD

**Issue by ThamarD** [bitsongofficial/delegation-program#51]
### Validator address

bitsong1d9mue6sxrxgcd8rz6cdmeamw4cey3c24smrcc0

### On Chain Data

- [X] I confirm to have set my validator information on chain

### Contact information

Discord: thamar@6243 Telegram: https://t.me/forger123 Website: https://cosmos.thamar.net/

### Application categories

Uptime, Commission restake, Self delegation, Participation in the BitSong ecosystem, None core development

### Details

**Uptime** - My mainnet validator has already a high uptime, I keep a backup ready at all times.

**Commission restake** - Currently we daily restake 100% of the rewards and 100% of the commission with our own BitSong redelegation script which is open source and available on our Git repository. 

**Self delegation** - at the moment we have delegated 61k BTSG to our Thamar validator, which is more than 11%!

**Participating in Bitsong ecosystem** - Commitment to BitSong: "We are here to build a future in a music industry!"
Thamar is really an early testnet delegate! From the beginning, we suport BitSong, starting from Testnet-1 till Testnet-4, never missed! We always continue to participate actively in all the tests conducted in a testnet (e.g. fantoken-test; sinfonia)

**None core development** - Thamar has already created and open sourced through Github the "Bitsong reinvestment script for rewards and commission" and we maintain it [https://github.com/ThamarD/bitsong-scripts](https://github.com/ThamarD/bitsong-scripts).
Future we want to create a dashboard to create an overview of all validators important node information in one place, as we already did for the DPoS eco-system (ARK, SXP etc.), example: [https://github.com/ThamarD/dpos-dashboard](https://github.com/ThamarD/dpos-dashboard).

### Goals

Our goal is to have a long-term commitment with BitSong and we do that with the following contributions:

- We will participate in voting procedures
- We will continue in helping with new features when they need to be tested
- We continue to self-delegate the rewards and commission
- We continue to provide a secure stable validator with high uptime
- We will provide tech assistance in solving problems at times of crisis
- We build tooling to help validators in operating their nodes

### Timetable

The goals are mostly a continuous process.
The Non core development should be started in a couple of months and be ready as MVP end of November 2022.

**Comment by ctrl-Felix** [comment]
Valdiator: bitsongvaloper1d9mue6sxrxgcd8rz6cdmeamw4cey3c243ll3gj
