### ISSUE TITLE
EZStaking x BitSong

### ISSUE THREAD

**Issue by keupsonite** [bitsongofficial/delegation-program#52]
### Validator address

bitsongvaloper18xfqngs09n7a86lesrh4q5atjx37a3qc56hqhw

### On Chain Data

- [x] I confirm to have set my validator information on chain

### Contact information

Zak | EZStaking.io | FR#4931

### Application categories

Uptime, Commission restake, Self delegation, Participation in the BitSong ecosystem, Core development, Running relayers, Running an public rpc/api

### Details

**Uptime**: more than 98%

**Commission restake**: For the time being, we are redelegating all our commissions. There are no plans to change this at this time, it would be a real shame to sell at this price.

**Self restake**: We restake 100% of our commission from our withdraw-address: `bitsong1gjtvly9lel6zskvwtvlg5vhwpu9c9wawhdqlq6`.

**Participation in the BitSong ecosystem/Core development**: At the moment we don't really contribute to the BitSong ecosystem outside of the testnets and except for tweets/retweets on our Twitter, but if you have project ideas, needs, we can make ourselves available. 

**Running relayers**: We can relay all the chains we're present as validator (please see our website: https://ezstaking.io). For example: JUNO, Gravity Bridge, Stargaze, Comdex, OmniFlix, KiChain, CHEQD, Nym. Please let us know your needs.

**Running an public RPC/LCD**: https://rpc.bitsong.ezstaking.io, https://lcd.bitsong.ezstaking.io. Statesync is also available with the RPC node.

**Our Cosmos contributions**:  
- https://github.com/keupsonite/cosmos-autostaking
- https://github.com/EZStaking/ez_utilities
- https://github.com/cheqd/cheqd-node/pull/323/files
- https://github.com/BitCannaGlobal/web-wallet/issues/4#issuecomment-997315415
- https://github.com/lum-network/wallet/pull/51
- https://github.com/lum-network/sdk-javascript/pull/36
- https://github.com/CosmosContracts/incident-response/commits?author=keupsonite

**Comment by ctrl-Felix** [comment]
[BitSong Delegation Points Calculator - Validator Points-1.pdf](https://github.com/bitsongofficial/delegation-program/files/8804181/BitSong.Delegation.Points.Calculator.-.Validator.Points-1.pdf)

Score: 1025

**Comment by ctrl-Felix** [comment]
New Score: 1197
https://l.ctrl-felix.de/bOkhG

(Missing self stake from external address)
