### ISSUE TITLE
UbikCapital

### ISSUE THREAD

**Issue by UbikCapital** [bitsongofficial/delegation-program#53]
### Validator address

bitsongvaloper12a627cpjyez9ne06nttzqrgt067znnhqqlguv0

### On Chain Data

- [X] I confirm to have set my validator information on chain

### Contact information

contact@ubik.capital

### Application categories

Uptime, Commission restake, Self delegation

### Details

Uptime
Commission restake
Self delegation
Participation in the BitSong ecosystem

**Comment by ctrl-Felix** [comment]
Score: 480
https://l.ctrl-felix.de/eIRb9

Thank you for your application
