### ISSUE TITLE
OranG3cluB

### ISSUE THREAD

**Issue by Vasya-kripto** [bitsongofficial/delegation-program#55]
### Validator address

bitsongvaloper1up87cpxu86wv30k4d2g8tzhhqcka3n5mhmuf4f

### On Chain Data

- [X] I confirm to have set my validator information on chain

### Contact information

https://twitter.com/orang336462045
Discord: OranG3#1415
orang3club@gmail.com

### Application categories

Uptime, Commission restake, Self delegation, Participation in the BitSong ecosystem, Se

### Details

https://explorebitsong.com/validators/bitsongvaloper1up87cpxu86wv30k4d2g8tzhhqcka3n5mhmuf4f

### Goals

Be the best validator! :-)

**Comment by ctrl-Felix** [comment]
Hi, unfortunately you have no picture and no website (which can be a zg link, twitter link, etc.). Please update this asap to be eligible

**Comment by Vasya-kripto** [comment]
https://twitter.com/orang336462045

**Comment by ctrl-Felix** [comment]
> https://twitter.com/orang336462045

I meant on chain. Can you please set a website (maybe your twitter) and a logo to your validator and submit a Pull request to mintscan to request them to add it

**Comment by CommunityStaking** [comment]
Score: 1272
https://l.ctrl-felix.de/xIT6y
In the absence of percentage of commission restake we used 40%.
