### ISSUE TITLE
dreamstaker

### ISSUE THREAD

**Issue by dreamstaker** [bitsongofficial/delegation-program#56]
### Validator address

bitsongvaloper1gktsym0w2xvutpqe8a9tvs6c4qrts8wnt8nnfp

### On Chain Data

- [x] I confirm to have set my validator information on chain

### Contact information

https://twitter.com/Anna27057333
Anna1242#2262

### Application categories

Uptime, Commission restake, Participation in the BitSong ecosystem

### Details

https://explorebitsong.com/validators/bitsongvaloper1gktsym0w2xvutpqe8a9tvs6c4qrts8wnt8nnfp

**Comment by CommunityStaking** [comment]
Hello dreamstaker, please make sure you have the prerequisites of the delegation program covered asap or you will lose the BitSong delegation.

**Comment by freak12techno** [comment]
@ctrl-Felix if I evaluated it correctly, the eventual score is 1200: https://l.ctrl-felix.de/dhQAr
one thing I noticed is that this validator doesn't have neither description, nor mintscan logo, nor website

**Comment by ctrl-Felix** [comment]
@dreamstaker please set your website and do the pull request to get your logo on mintscan asap

**Comment by dreamstaker** [comment]
Everything is done :-)
