### ISSUE TITLE
Simply Staking

### ISSUE THREAD

**Issue by Simply-VC** [bitsongofficial/delegation-program#57]
### Validator address

bitsongvaloper129y6g55wz7mz9vs2nudfvfdaun80fuphnltfpf

### On Chain Data

- [X] I confirm to have set my validator information on chain

### Contact information

staking@simply-vc.com.mt

### Application categories

Uptime, Commission restake, Self delegation

### Details

We strive to maintain very high uptime, running all of our nodes out of our own geo-distributed datacentres.
We also plan to keep our self delegation, and keep increasing it every month.

**Comment by ctrl-Felix** [comment]
Score: 60
https://l.ctrl-felix.de/Adb3F

Thank you very much for your application
