### ISSUE TITLE
cyberG

### ISSUE THREAD

**Issue by Vgk88** [bitsongofficial/delegation-program#58]
### Validator address

bitsongvaloper1m8ps45ltlt0vejjm2hqtu26jkd8rfkz9vwu5tw

### On Chain Data

- [X] I confirm to have set my validator information on chain

### Contact information

cyberG#4889/cryptoq11/88vgk88@gmail.com

### Application categories

Uptime, Commission restake, Self delegation, Participation in the BitSong ecosystem, Running relayers, Running an public rpc/api

### Details

I participate in Bitsong from the testnet. I want to continue to be a validator in Bitsong. I plan to participate more actively in the life of the community and help with the development of the Ukrainian Bitsong community. I will also help with the development of infrastructure for Bitsong. Ready to launch IBС relays and RPC / API nodes. I plan to provide good uptime for the network.

### Goals

Be useful to the Bitsong community and do a good job as a validator by providing uninterrupted uptime and actively participating in voting. I want help with the development of infrastructure and tools. I plan to participate in future Bitsong tetsnets.

### Timetable

I can run RPС node right after the delegation. I can launch the relayer within a week after . I will participate in the life of the community on an ongoing basis.

**Comment by Vgk88** [comment]
Want to restake 100%

**Comment by CommunityStaking** [comment]
Hello cyberG, please make sure you have the prerequisites of the delegation program covered asap or you will lose the BitSong delegation.

**Comment by ctrl-Felix** [comment]
Score: 1770
https://l.ctrl-felix.de/A2Hzg

This is calculated without RPC and relayers. If you want to launch them please inform me and I will add it to the calculation.

**Comment by Vgk88** [comment]
I can run RPC and relayer  this week.

**Comment by ctrl-Felix** [comment]
> I can run RPC and relayer this week.

If so can you do it and provide me the link and relayer account address please?

**Comment by Vgk88** [comment]
Of course. I will provide all links as soon as the work is ready.

**Comment by Vgk88** [comment]
My RPC : http://65.108.41.172:20657/
