### ISSUE TITLE
cryptobtcbuyer 

### ISSUE THREAD

**Issue by cryptobtcbuyer** [bitsongofficial/delegation-program#59]
### Validator address

bitsongvaloper17dpklyxlrn9kypkd3khy9t98v8qddnghllnt7x

### On Chain Data

- [X] I confirm to have set my validator information on chain

### Contact information

cryptobtcbuyer#1335 
[t.me/cryptobtcbuyer ](https://t.me/cryptobtcbuyer)
cryptobtcbuyer@gmail.com

### Application categories

Uptime, Commission restake, Self delegation, Participation in the BitSong ecosystem, Running an public rpc/api

### Details

**Uptime**
Ensuring high uptime 24/7 with the help of notification and monitoring systems

**Commission restake**
The first 3 months are 100% commission restake. After that time I would like to estimate the cost of maintaining the servers. But even in this case, I do not think that the restake will be below 70%, and perhaps it will also remain 100%

**Participation in the BitSong ecosystem**
Participation in community discussions, voting for suggestions, spred info about Bitsong, helping other validators and users in the discord, suggestions for improving current products in the Bitsong ecosystem, participation in testnets, searching for bugs.

**Running an public rpc/api**
Launching a public RPC for the needs of the validator community

### Goals

Assistance to the project and, in this regard, improvement of their own skills.  Long-term participation in the project.

### Timetable

Participation in the life of the project — daily)
Running an public rpc/api — It's a matter of a few days

**Comment by ctrl-Felix** [comment]
Hello, can you provide me the link to your public rpc/api node please?

**Comment by cryptobtcbuyer** [comment]
> Hello, can you provide me the link to your public rpc/api node please?
**Public RPC**:  http://207.244.253.244:26657/status

SNAP_RPC="http://207.244.253.244:26657"

LATEST_HEIGHT=$(curl -s $SNAP_RPC/block | jq -r .result.block.header.height); \
BLOCK_HEIGHT=$((LATEST_HEIGHT - 100)); \
TRUST_HASH=$(curl -s "$SNAP_RPC/block?height=$BLOCK_HEIGHT" | jq -r .result.block_id.hash)

echo $LATEST_HEIGHT $BLOCK_HEIGHT $TRUST_HASH

peers="9335bd93fc50365bcf4db2b9e15062c9d4a33c0b@207.244.253.244:26656"
sed -i.bak -e "s/^persistent_peers *=.*/persistent_peers = \"$peers\"/" $HOME/.bitsongd/config/config.toml

**Comment by ctrl-Felix** [comment]
Hi, unfortunately you didn't vote on the last governance proposal. This governance proposal was mandatory to vote to be eligible for this period. There will be new proposals before the next epoch so that you can vote and be eligible.

**Comment by cryptobtcbuyer** [comment]
> Hi, unfortunately you didn't vote on the last governance proposal. This governance proposal was mandatory to vote to be eligible for this period. There will be new proposals before the next epoch so that you can vote and be eligible.

Yes, you're right. I joined after this proposals was accepted

**Comment by ctrl-Felix** [comment]
Okay @cryptobtcbuyer 
Can you please do the pull request to mintscan to get your logo to mintscan?

**Comment by cryptobtcbuyer** [comment]
> Can you please do the pull request to mintscan to get your logo to mintscan?

done:
https://github.com/cosmostation/cosmostation_token_resource/pull/2294
need to wait for the merged
