### ISSUE TITLE
moonsoon

### ISSUE THREAD

**Issue by tt1000vv** [bitsongofficial/delegation-program#60]
### Validator address

bitsongvaloper1nw4wmjq7le0h993tn27kmnqk2y8mdvhutzklgk

### On Chain Data

- [X] I confirm to have set my validator information on chain

### Contact information

tt1000#6541 / tt1000@protonmail.com 

### Application categories

Uptime, Commission restake, Self delegation, Participation in the BitSong ecosystem, Running an public rpc/api

### Details

Long term fan of the Bitsong project. I try to follow all the events in the project. I try to provide the best uptime and active participation in network updates. I am ready to launch the RPS node and everything the project needs.

### Goals

My goal is to ensure the stable operation of the validator. I try to keep my node running smoothly. I am ready to help with the improvement of Bitsong's infrastructure. I will try to help the Bitsong community.

### Timetable

Ready to start as soon as possible.

**Comment by ctrl-Felix** [comment]
[BitSong Delegation Points Calculator - Validator Points.pdf](https://github.com/bitsongofficial/delegation-program/files/8804131/BitSong.Delegation.Points.Calculator.-.Validator.Points.pdf)

Score: 918

**Comment by tt1000vv** [comment]
Will restake 100%

**Comment by CommunityStaking** [comment]
Hello moonsoon, please make sure you have the prerequisites of the delegation program covered asap or you will lose the BitSong delegation.

**Comment by tt1000vv** [comment]
My RPC: http://135.181.138.160:29657/
