### ISSUE TITLE
CryptoCrew Validators

### ISSUE THREAD

**Issue by clemensgg** [bitsongofficial/delegation-program#61]
### Validator address

bitsongvaloper1wetqg989uyj3mpk07h8yt3qvu2cdlsv7fp3zda

### On Chain Data

- [X] I confirm to have set my validator information on chain

### Contact information

Discord: Claimens#3460
Telegram: [@clemensg](https://t.me/clemensg)
Email: support@ccvalidators.com
Public Git Repo: [CryptoCrew-Validators](https://github.com/clemensgg/CryptoCrew-Validators)

Website: [ccvalidators.com](https://ccvalidators.com)

### Application categories

Uptime, Commission restake, Self delegation, Participation in the BitSong ecosystem, Running relayers, Running an archive node, Running an public rpc/api

### Details

- over 99% uptime and no slashing since 10/2021
- sentry nodes & multi-party threshold signer
- contributing core infrastructure
- running ibc relayers to cosmoshub, osmosis, juno network

### Goals

maximize onchain & ibc ux

### Timetable

ongoing

**Comment by ctrl-Felix** [comment]
Hi Claimens, thank you very much for your application. Can you please give me the link to your public api/rpc endpoints to add them to our monitoring? And are these public endpoints a archive node?

**Comment by ctrl-Felix** [comment]
[BitSong Delegation Points Calculator - CryptoCrew-1.pdf](https://github.com/bitsongofficial/delegation-program/files/8804103/BitSong.Delegation.Points.Calculator.-.CryptoCrew-1.pdf)

Score: 448 pts
