### ISSUE TITLE
Thamar proposal - Bitsong reinvestment script for rewards and commissions

### ISSUE THREAD

**Issue by ThamarD** [bitsongofficial/delegation-program#7]
## Type of Proposal

- [ ] Feature Request (e.g. functionality)

- [ ] Economic Model

- [ ] Underlying Technology (e.g. performance)

- [x] Application Development

- [ ] Marketing/Community Building

- [ ] Communication Channels

- [ ] Documentation

- [ ] Others

## Background
Hi, my name is Thamar and I run a mainnet validator with the same name [.](https://explorebitsong.com/staking/bitsongvaloper1d9mue6sxrxgcd8rz6cdmeamw4cey3c243ll3gj). I have participated in all the testnets of Bitsong and hope to be of help in this also in the future.

## Describe The Proposal (No more than 50 words)
My proposal is to create the following: "Bitsong reinvestment script for rewards and commission".
The bash based linux script can be run next to your node or on a seperate machine.

## Business Model (Optional for underlying technology)
The provided script enable Validators and delegators to claim their staking rewards and reinvest them, to receive compounded interest. In addition to this, it supports withdrawal of validator commission.

## Expected Outcome
The deliverable will be a script with an installation instruction on my GitHub.

## Contact Information
TG: Thamar
Discord: Thamar

## For Admin Use

- [ ] Not duplicate proposal
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ThamarD** [comment]
Hi all, 

An update for my proposal.
I have created and tested the first version of my promissed proposal, my "Bitsong reinvestment script"!
You can find it here: [https://github.com/ThamarD/bitsong-scripts](url)

If you have feedback, please let me know.

BR, Thamar!

**Comment by ThamarD** [comment]
Hi all,

I have updated teh version "Bitsong reinvestment script" for the new mainnet bitsong-2b!
You can find it here: https://github.com/ThamarD/bitsong-scripts

If you have feedback, please let me know.

BR, Thamar!

**Comment by angelorc** [comment]
that's cool, we should add it in our docs https://docs.bitsong.io

If you can write a tutorial I will be happy to put it there
