### ISSUE TITLE
freak12techno - Application for the delegation from the Bitsong DAO

### ISSUE THREAD

**Issue by freak12techno** [bitsongofficial/delegation-program#75]
### Validator address

bitsongvaloper14rvn7anf22e00vj5x3al4w50ns78s7n42rc0ge

### On Chain Data

- [X] I confirm to have set my validator information on chain

### Contact information

t.me/freak12techno, freak12techno | Validator#1151, freak12techno@gmail.com

### Application categories

Uptime, Commission restake, Self delegation, Participation in the BitSong ecosystem, None core development, Running an public rpc/api

### Details

Hi there. We do a lot for the comminity (see https://freak12techno.github.io/validators), here's what's related to Bitsong:
1) we maintain a public RPC/API endpoint (https://rpc.bitsong.freak12techno.io, https://api.bitsong.freak12techno.io)
2) we were never jailed and have top-notch monitoring/alerting system to avoid that, on top of that we even wrote some posts on our telegram channel (https://t.me/freak12techno_validator) regarding our setup and insights
3) we maintain a set of ansible playbooks to bootstrap a fullnode, including Bitsong one: https://github.com/freak12techno/ansible-cosmos)
4) so far, we stake 100% of the rewards to ourself
5) we maintain a few tools for observability, namely https://github.com/freak12techno/cosmos-wallets-exporter (balance metrics for Prometheus), https://github.com/freak12techno/cosmos-validators-exporter (validators stats for Prometheus), https://github.com/freak12techno/cosmos-proposals-checker (tool to notify you if you missed a proposal vote for an ongoing proposal), see all of them on https://github.com/freak12techno
6) we maintain a tool to notify on validators' missed blocks tailored for Bitsong, see https://t.me/bitsong_missed
7) we helped a bit by providing input for the delegation program criteria last epoch and plan to do so in the current one, if needed
8) we added a script for calculating votings percentage for this repository, which can likely be improved and used later for this evaluation
9) we came up with prop 14 to increase deposit fee for proposals, likely making it harder for spammers to get into and shill their stuff, and as a validator we haven't missed a single proposal vote from prop 11 onwards
10) lastly, we presented Bitsong to Russian Cosmos community by making a speech on weekly calls, describing the project goals/roadmap/internals and answering questions. We also try to answer any questions people may face in Russian comminuty (not only regarding Bitsong, but Bitsong-related as well).

Bitsong is one of the projects we're mostly involved with, so it's nice to do something for the community.

Thanks for your time reading this, and let us know (here or in any other place we've mentioned in contacts) if there are more answered needed).
See you, and hope this evaluation goes smooth!

### Goals

Earn tokens and stake them back.

### Timetable

We plan to restake all of our revenue for the whole next epoch (as it's small enough for now and practically won't be enough for paying even for 1 month of renting our servers), treating this validator as a long-term investment.

**Comment by CommunityStaking** [comment]
Hi @freak12techno please let me know what percentage you are 100% certain going to restake of your validators commission during the upcoming epoch.

**Comment by CommunityStaking** [comment]
Score: 3235
https://l.ctrl-felix.de/kirQW

Thank you for your application
