### ISSUE TITLE
Imperator.co Proposal

### ISSUE THREAD

**Issue by imperator-co** [bitsongofficial/delegation-program#8]
## Type of Proposal

- [X] Application Development

- [X] Marketing/Community Building

- [X] Documentation

## Background

We are two Data Engineers with many of experience at your service, while we maintain a fully transparent operation.
Our years of experience in Big Data allowed us to take the best of it and adapt it to the proof-of-stake world. Therefore, we have developed and adapted modules initially used in Big Data for our fully customized infrastructure service. The latest technologies in terms of high availability, security and efficiency are naturally present in our system.
We are working with a single-node validator with an active-standby setup, if the active node dies, we ensure the active node is actually dead and then manually promote the standby node. This allows us to safely avoid the penalty for inconsistency (double signing) and keep a close 100% uptime. Every node is hardened and protected by a strict firewall.

## Describe The Proposal (No more than 50 words)

- Propose a monitoring and alerting system as SaaS or OnPremise, we are in development phase to integrate projects on which we are validators, and hoping to integrate a similar service for Bitsong.
Website : https://chainprobes.io/
- Grow the community through different contests, improve the documentation and create mutual help between validators and contributors of the project on different channels (Discord, Telegram...)

## Expected Outcome

- Added value to the project through our Big Data expertise
- Secured the blockchain and made the services reliable
- Contributed to the growth of the project and promoted it on various social networks.
- Create a centralized monitoring and alerting platform for validators 

## Timetable

Monitoring and Alerting Platform: ~Octobre 2021 (under development)
For competitions, this will be done throughout the project.

## Contact Information

Mail : contact@imperator.co
Telegram : @xImpe / @ibrmakaveli
Website : https://imperator.co

## For Admin Use

- [ ] Not duplicate proposal
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by BitGlad1** [comment]
Hi there,

Thanks for your proposal.

Please fill in also the Timetable and explain a little bit more in details which kind of contests are you aiming to create/run and how would that be contributing to the Ecosystem Growth.

Regards

**Comment by imperator-co** [comment]
Hi,

I added the Timetable, and for the contests, you can find examples that we have done on Twitter here: https://twitter.com/imperator_co/status/1382426930968989703
This will help to spread the word about the Bitsong project, plus we plan to make a Staking Guide like this one too:
https://imperator-co.medium.com/ki-chain-xki-complete-staking-guide-imperator-co-9acb78b406be

Moreover, we also have an Architectute and DevOps expertise which can be interesting for the technical part (specific needs: Dev, Ops etc...): we both currently work in the Big Data domain.
We are also part of a community of enthusiastic investors and plan to make several partners with investment funds.

Best regards
